apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: ticket-lab
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
    - name: http
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: ticket-lab
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: inventory
      containers:
        - name: inventory
          image: ticket-resilience-lab-inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgresql://ticket:ticket@postgres:5432/ticketdb
            - name: DEFAULT_EVENT_ID
              value: concert-1
            - name: DEFAULT_SEATS
              value: "10"
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 8
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
